# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbdac78297168f3b19c88ce79cafed2383378481aa292706bd4c0d2f6ada86c09532fa73c4fb81949745c3cdaa451c4a8a2442f169f63a04cfe0fb98c2396767

test:
  secret_key_base: 3bf8d186a9ea38b3b2bf0695f731235f455486837584a0c99393793bf3afec420bfe9dd57632963209d1877ada0724c4a91f7f4035112d2800a16d505c8e986c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
